### ISSUE TITLE
Semicolon at the end of path breaks add command

### ISSUE THREAD

**Issue by teelahti** [vivainio/wpathr#1]
If path has a semicolon in the end, say: 

```
c:\windows\system32;c:\foo;
```

and you call 

```
wpathr add --commit "c:\bar"
```

resulting path is 

```
c:\windows\system32;c:\foo;;c:\bar
```

which does not work on Windows.

**Comment by vivainio** [comment]
"add" now treats the trailing semicolon properly. "remove", "squash", "exists" etc now strip all semicolons in the middle while doing other manipulation (if --commit is given). Reopen if bug reproduces.
